### ISSUE TITLE
Add shortened urls in readme file

### ISSUE THREAD

**Issue by tkeer** [Pharaonic/laravel-short-url#1]
Add resulted shorted urls in examples in readme file.

**Comment by Pharaonic** [comment]
@tkeer do you mean https://github.com/Pharaonic/laravel-short-url#get-url ?

> echo shortURL('3dc0c3deda')->url;    //      http://127.0.0.1:8000/8ca3522787

**Comment by tkeer** [comment]
Nice, would it be possible to have it for all examples?

**Comment by Pharaonic** [comment]
> Nice, would it be possible to have it for all examples?

like this ? 
https://github.com/Pharaonic/laravel-short-url/blob/main/README.md

**Comment by tkeer** [comment]
Doesn't this package shorten the url, for example it converts something like this `/please/shorten/my/url` to `/1324d233`? I was suggesting to include shortened urls in the examples too. 

For example

```
// Generate from URL
shortURL()->generate('https://pharaonic.io/users/secret/classes/tables');

// It will generate
https://pharaonic.io/234ldf2
```



```

**Comment by Pharaonic** [comment]
> For example
> 
> ```
> // Generate from URL
> shortURL()->generate('https://pharaonic.io/users/secret/classes/tables');
> 
> // It will generate
> https://pharaonic.io/234ldf2
> ```


but you have to know that `generate` method returns object not an URL
but if you have any edit on documentation just do it then pull request to merge and i will review it then will accept it ;)
