### ISSUE TITLE
Model issue

### ISSUE THREAD

**Issue by gowthambopathyraj** [Pharaonic/laravel-short-url#2]
Hi Team, 

I have implemented laravel framework 6.2.

After installed, click the button showing 404 error.
Please check the attached image,
How to solve the issue???
![image](https://user-images.githubusercontent.com/38747811/146317933-19408143-fb1d-4697-b976-844296971286.png)

**Comment by MoamenEltouny** [comment]
@gowthambopathyraj can you show me your code snippet please ?

**Comment by gowthambopathyraj** [comment]
I installed composer itself.

After, I mentioned this code in blade file.
But, whole project not working showing 404 error.



```
// Generate from URL
$test = shortURL()->generate($desktop_url, \Carbon\Carbon::now()->addMinute());
echo $test;
```

**Comment by MoamenEltouny** [comment]
`$test = shortURL()->generate(url()->current(), \Carbon\Carbon::now()->addMinute());`

@gowthambopathyraj  it's working very well for me over Laravel 6 till 8, i think there is something wrong with your vendor please re-install the package then migrate

**Comment by gowthambopathyraj** [comment]
Hi,

This code put in test.blade.php page.

In assessment/index.blade.php
Page not working showing 404 error.

In particular test.blade.php page its working fine.


Thanks
Gowtham Boopathiraj
